services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-my
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network

  mariadb:
    image: mariadb:latest
    container_name: mariadb-my
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DB}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

  nestjs-app:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nestjs-app
    ports: []
    depends_on:
      - mariadb
      - rabbitmq
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DB: ${DB_DB}
      RABBITMQ_URL: amqp://rabbitmq-my:5672
    env_file:
      - .env
    networks:
      - app-network
    restart: always

  front-end:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: nextjs-app
    ports:
      - "3000:3000"
    networks:
      - app-network
    restart: always

  nginx:
    image: nginx:latest
    container_name: reverse_proxy
    volumes:
      - ./server/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "5500:5500"
    depends_on:
      - nestjs-app
      - front-end
    networks:
      - app-network
    restart: always

volumes:
  rabbitmq_data:
  mariadb_data:

networks:
  app-network:
    driver: bridge
