export enum KEY_OF_INJECTION {
  USER_REPOSITORY = 'USER_REPOSITORY',
  REPOS_REPOSITORY = 'REPOS_REPOSITORY',
  AUTH_QUEUE = 'AUTH_QUEUE',
  REPO_QUEUE = 'REPO_QUEUE',
}
export enum JOB {
  UPDATE_REPO_JOB = 'UPDATE_REPO_JOB',
  CREATE_REPO_JOB = 'CREATE_REPO_JOB',
}
